# Generated by Django 3.1.2 on 2021-02-06 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('event', models.TextField(null=True)),
                ('information', models.TextField(null=True)),
                ('date', django_jalali.db.models.jDateField(null=True)),
                ('username', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
