# Generated by Django 3.1.2 on 2021-12-04 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0002_event_tousers'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_copy',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstname', max_length=255)),
                ('lastname', models.CharField(db_column='lastname', max_length=255)),
                ('post', models.CharField(db_column='post', max_length=255)),
                ('tell', models.IntegerField(blank=True, db_column='tell')),
                ('image', models.ImageField(blank=True, db_column='image', null=True, upload_to='pictures/')),
                ('postid', models.IntegerField(db_column='postid', default=1)),
                ('Email', models.CharField(db_column='Email', max_length=255, null=True)),
                ('managerid', models.IntegerField(db_column='managerid', null=True)),
                ('mobile', phone_field.models.PhoneField(blank=True, default=0, max_length=31)),
                ('birthdate', django_jalali.db.models.jDateField(null=True)),
                ('EmploymentDate', django_jalali.db.models.jDateField(null=True)),
                ('username', models.ForeignKey(db_column='username', max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
