# Generated by Django 3.1.2 on 2021-12-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20211204_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee_copy',
        ),
    ]
